database:
  #数据库类型，可选值：mongodb,sqlite
  database_type: "sqlite"
  #数据库连接信息
  mongodb:
    # MongoDB数据库连接地址
    url: "mongodb://127.0.0.1:27017"
    # MongoDB数据库名称
    db_name: "user_database"
  sqlite:
    # SQLite数据库文件路径
    path: "res/user.db"
  #管理界面密码
  admin_password: "0000"
